name: Release

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  packagist:
    name: Notify Packagist
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Packagist update
        run: |
          curl -sf -XPOST \
            -H 'content-type: application/json' \
            "https://packagist.org/api/update-package?username=${PACKAGIST_USERNAME}&apiToken=${PACKAGIST_TOKEN}" \
            -d '{"repository":{"url":"https://packagist.org/packages/xen3r0/adf-converter"}}'
        env:
          PACKAGIST_USERNAME: ${{ secrets.PACKAGIST_USERNAME }}
          PACKAGIST_TOKEN: ${{ secrets.PACKAGIST_TOKEN }}
